Repository aimclub/GOLEM, pull requests merged in 2023-10, with the labels that each got.

#197 Plot of agent mutations probabilities and actions expectations
  examples/experiment_analyzer/experiment_analyzer.py
  experiments/experiment_analyzer.py
Labels: enhancement

#187 168 minor agent log output enhancement
  examples/adaptive_optimizer/context_mab_experiment_different_targets.py
  examples/adaptive_optimizer/experiment_setup.py
  examples/adaptive_optimizer/mab_experiment_different_targets.py
  examples/adaptive_optimizer/neural_mab_experiment_different_targets.py
  examples/synthetic_graph_evolution/graph_search.py
  golem/core/optimisers/adaptive/mab_agents/contextual_mab_agent.py
  golem/core/optimisers/adaptive/operator_agent.py
  golem/core/optimisers/genetic/operators/mutation.py
  other_requirements/adaptive.txt
Labels: bug

#211 Integration tests fix
  golem/core/optimisers/adaptive/neural_mab.py
  other_requirements/adaptive.txt
Labels: bug

#219 Fix reported bugs
  golem/core/optimisers/populational_optimizer.py
Labels: bug

#138 Add infrastructure for offline pretraining of Bandits
  examples/molecule_search/experiment.py
  examples/molecule_search/mol_adapter.py
  examples/molecule_search/mol_graph.py
  golem/core/adapter/nx_adapter.py
  golem/core/optimisers/adaptive/agent_trainer.py
  golem/core/optimisers/adaptive/common_types.py
  golem/core/optimisers/adaptive/experience_buffer.py
  golem/core/optimisers/adaptive/history_collector.py
  golem/core/optimisers/adaptive/mab_agents/contextual_mab_agent.py
  golem/core/optimisers/adaptive/mab_agents/mab_agent.py
  golem/core/optimisers/adaptive/mab_agents/neural_contextual_mab_agent.py
  golem/core/optimisers/adaptive/operator_agent.py
  golem/core/optimisers/adaptive/reward_agent.py
  golem/core/optimisers/fitness/fitness.py
  golem/core/optimisers/genetic/evaluation.py
  golem/core/optimisers/genetic/operators/mutation.py
  golem/core/optimisers/objective/objective.py
  golem/core/optimisers/opt_history_objects/opt_history.py
  golem/core/utilities/data_structures.py
Labels: adaptive, opt core
